# Numpy Exercise...Good Luck

import numpy as np

Create an array of 5 zeros

Create an array of 10 ones

Create an array 10 six

Create an array of integer from 10 to 70

Create a 5x5 matrix with values ranging from 0 to 25

Create 3x3 identity matrix

Use numpy to generate a random number between 0 and 1

Use numpy to generate an array of 30 numbers sampled from a standard normal distribution

Create an array of 15 linearly spaced points between 0 and 1

# Numpy Indexing and Selection

In [6]:
#Run this cell for solving further questions
input_mat = np.arange(1,26).reshape(5,5)
input_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#Write your code here to replicate the same output below


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [10]:
#Write your code here to replicate the same output below

20

In [ ]:
#Write your code here to replicate the same output below

array([[ 2],
       [ 7],
       [12]])

In [14]:
#Write your code here to replicate the same output below

array([21, 22, 23, 24, 25])

Get the sum of all values in input_mat

Get the standard deviation of values in input_mat

Get the sum of all columns in input_mat

Write a code in such a way that we get same random number each time we run the cell